// Mermaid theme aligned with design.md tokens — base theme + themeVariables per mode.

const FONT_STACK = 'system-ui, -apple-system, BlinkMacSystemFont, "Inter", sans-serif';

const dark = {
  theme: "base" as const,
  themeVariables: {
    background: "#1a1d27",
    mainBkg: "#242838",
    primaryColor: "#242838",
    secondaryColor: "#1a1d27",
    tertiaryColor: "#0f1117",
    primaryTextColor: "#e2e8f0",
    secondaryTextColor: "#e2e8f0",
    tertiaryTextColor: "#8892a4",
    titleColor: "#e2e8f0",
    primaryBorderColor: "#2d3148",
    secondaryBorderColor: "#2d3148",
    tertiaryBorderColor: "#2d3148",
    nodeBorder: "#2d3148",
    clusterBkg: "#242838",
    clusterBorder: "#2d3148",
    lineColor: "#8892a4",
    edgeLabelBackground: "#1a1d27",
    actorBkg: "#242838",
    actorBorder: "#2d3148",
    actorTextColor: "#e2e8f0",
    actorLineColor: "#2d3148",
    signalColor: "#8892a4",
    signalTextColor: "#e2e8f0",
    labelBoxBkgColor: "#242838",
    labelBoxBorderColor: "#2d3148",
    labelTextColor: "#e2e8f0",
    loopTextColor: "#e2e8f0",
    activationBorderColor: "#8892a4",
    activationBkgColor: "#242838",
    noteBkgColor: "#1f2235",
    noteTextColor: "#e2e8f0",
    noteBorderColor: "#2d3148",
    fontFamily: FONT_STACK,
    fontSize: "13px",
  },
  gantt: {
    axisFormat: "%m-%d",
    barGap: 10,
    barHeight: 18,
    fontSize: 12,
    gridLineStartPadding: 28,
    leftPadding: 95,
    rightPadding: 90,
    sectionFontSize: 13,
    tickInterval: "1week",
    topPadding: 56,
    useWidth: 980,
    weekday: "monday" as const,
  },
};

const light = {
  theme: "base" as const,
  themeVariables: {
    background: "#ffffff",
    mainBkg: "#f0f0f5",
    primaryColor: "#f0f0f5",
    secondaryColor: "#f5f5f7",
    tertiaryColor: "#ffffff",
    primaryTextColor: "#1d1d1f",
    secondaryTextColor: "#1d1d1f",
    tertiaryTextColor: "#1d1d1f",
    titleColor: "#1d1d1f",
    primaryBorderColor: "#d8d8df",
    secondaryBorderColor: "#d8d8df",
    tertiaryBorderColor: "#d8d8df",
    nodeBorder: "#d8d8df",
    clusterBkg: "#f5f5f7",
    clusterBorder: "#d8d8df",
    lineColor: "#6e6e73",
    edgeLabelBackground: "#ffffff",
    actorBkg: "#ffffff",
    actorBorder: "#d8d8df",
    actorTextColor: "#1d1d1f",
    actorLineColor: "#d8d8df",
    signalColor: "#6e6e73",
    signalTextColor: "#1d1d1f",
    labelBoxBkgColor: "#f0f0f5",
    labelBoxBorderColor: "#d8d8df",
    labelTextColor: "#1d1d1f",
    loopTextColor: "#1d1d1f",
    activationBorderColor: "#6e6e73",
    activationBkgColor: "#f0f0f5",
    noteBkgColor: "#fff8e1",
    noteTextColor: "#1d1d1f",
    noteBorderColor: "#d8d8df",
    fontFamily: FONT_STACK,
    fontSize: "13px",
  },
  gantt: {
    axisFormat: "%m-%d",
    barGap: 10,
    barHeight: 18,
    fontSize: 12,
    gridLineStartPadding: 28,
    leftPadding: 95,
    rightPadding: 90,
    sectionFontSize: 13,
    tickInterval: "1week",
    topPadding: 56,
    useWidth: 980,
    weekday: "monday" as const,
  },
};

export type MermaidConfig = typeof dark;

export function mermaidConfigFor(isDark: boolean): MermaidConfig {
  return isDark ? dark : light;
}
